blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/komandio-labs/komandio-extensions/security
    about: Do not disclose security issues in public issues.
